site_name: PraisonAI Documentation
site_url: https://docs.praison.ai
site_author: MervinPraison

repo_name: MervinPraison/PraisonAI
repo_url: https://github.com/MervinPraison/PraisonAI

nav:
  - 🏠 Home:
      - Home: home.md
      - TL;DR: tldr.md

  - ⚡ Getting Started:
      - Installation: installation.md
      - Initialise: initialise.md
      - Run: run.md
      - Full Automatic: auto.md
      - User Interface: ui.md
      - CrewAI: framework/crewai.md
      - AutoGen: framework/autogen.md

  - 🧠 Models:
      - Models: models.md
      - OpenAI: models/openai.md
      - Groq: models/groq.md
      - Google Gemini: models/google.md
      - Anthropic Claude: models/anthropic.md
      - Cohere: models/cohere.md
      - Mistral: models/mistral.md
      - Ollama: models/ollama.md
      - Other Models: models/other.md

  - ⚙️ Tools:
      - Tools: tools.md
      - Create Custom Tools: tools/custom.md
      - Tools Creator GPT: tools/gpt.md
      - DuckDuckGo: tools/duckduckgo.md
      - Langchain: tools/langchain.md
      - Firecrawl: firecrawl.md
      - Wikipedia: tools/wikipedia.md
      - YouTube: tools/youtube.md
      - Tavily: tools/tavily.md
      - Reddit: tools/reddit.md
      - You.com: tools/you.com.md
      - Crawl4AI: tools/crawl4ai.md

  - 📊 Monitoring:
      - AgentOps: monitoring/agentops.md

  - 📚 Developers:
      - Test: developers/test.md
      - Agents Playbook: developers/agents-playbook.md
      - Wrapper: developers/wrapper.md
      - Wrapper with Tools: developers/wrapper-tools.md
      - Google Colab: developers/googlecolab.md
      - Google Colab Tools: developers/googlecolab-tools.md
      - Deploy: deploy.md

  - 🤗 Contributing:
      - Contribute: contributing.md

  - 🛠️ API reference:
      - API: api.md
      - API Code: api/praisonai/index.html

theme:
  name: material

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: google
  # - glightbox
