name: "Claude Code Action"
description: "Custom Claude Code runner for PraisonAI"

inputs:
  anthropic_api_key:
    required: true
    description: "Anthropic API key"
  github_token:
    required: true
    description: "GitHub token for repo access"

runs:
  using: "docker"
  image: "docker://ghcr.io/mervinpraison/praisonai-claudecode:latest"
  env:
    ANTHROPIC_API_KEY: ${{ inputs.anthropic_api_key }}
    GITHUB_TOKEN: ${{ inputs.github_token }}
  args:
    - "--anthropic-api-key=${{ inputs.anthropic_api_key }}"
    - "--github-token=${{ inputs.github_token }}" 