name: Claude Code

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write
      packages: read
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Debug Environment
        run: |
          echo "=== Environment Debug ==="
          echo "GITHUB_ACTOR: $GITHUB_ACTOR"
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
          echo "GITHUB_REPOSITORY_OWNER: $GITHUB_REPOSITORY_OWNER"
          echo "GITHUB_TOKEN exists: $([ -n "$GITHUB_TOKEN" ] && echo "yes" || echo "no")"
          echo "GITHUB_TOKEN length: ${#GITHUB_TOKEN}"

      - name: Check Package Visibility
        run: |
          echo "=== Checking Package Visibility ==="
          curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               "https://api.github.com/users/MervinPraison/packages/container/praisonai-claudecode" \
               || echo "Package API call failed"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Test Docker Authentication
        run: |
          echo "=== Testing Docker Authentication ==="
          echo "Checking ~/.docker/config.json"
          cat ~/.docker/config.json | jq '.' || echo "No docker config found"
          echo "=== Testing Registry Access ==="
          curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
               "https://ghcr.io/v2/" || echo "Registry access failed"

      - name: Test Docker Pull
        run: |
          echo "=== Testing Docker Pull ==="
          echo "Attempting to pull image: ghcr.io/mervinpraison/praisonai-claudecode:latest"
          docker pull ghcr.io/mervinpraison/praisonai-claudecode:latest || echo "Pull failed with exit code: $?"
          echo "=== Checking Docker Images ==="
          docker images | grep praisonai-claudecode || echo "No images found"

      - name: Run Claude Code
        id: claude
        uses: ./.github/actions/claude-code-action
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

