name: Core Tests

on: 
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-core:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install UV
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.local/bin" >> $GITHUB_PATH


    - name: Install dependencies
      run: |
        cd src/praisonai
        uv pip install --system ."[ui,gradio,api,agentops,google,openai,anthropic,cohere,chat,code,realtime,call,crewai,autogen]"
        uv pip install --system duckduckgo_search
        uv pip install --system pytest pytest-asyncio pytest-cov

    - name: Set environment variables
      run: |
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY || 'sk-test-key-for-github-actions-testing-only-not-real' }}" >> $GITHUB_ENV
        echo "OPENAI_API_BASE=${{ secrets.OPENAI_API_BASE || 'https://api.openai.com/v1' }}" >> $GITHUB_ENV
        echo "OPENAI_MODEL_NAME=${{ secrets.OPENAI_MODEL_NAME || 'gpt-4o-mini' }}" >> $GITHUB_ENV
        echo "LOGLEVEL=DEBUG" >> $GITHUB_ENV
        echo "PYTHONPATH=${{ github.workspace }}/src/praisonai-agents:$PYTHONPATH" >> $GITHUB_ENV

    - name: Debug API Key Status
      run: |
        echo "🔍 Checking API key availability..."
        if [ -n "${{ secrets.OPENAI_API_KEY }}" ]; then
          echo "✅ GitHub secret OPENAI_API_KEY is available"
          echo "🔑 API key starts with: $(echo "$OPENAI_API_KEY" | cut -c1-7)..."
        else
          echo "⚠️ GitHub secret OPENAI_API_KEY is NOT set - using fallback"
          echo "🔑 Using fallback key: sk-test-key..."
        fi
        echo "🌐 API Base: $OPENAI_API_BASE"
        echo "🤖 Model: $OPENAI_MODEL_NAME"
        echo "🐛 Log Level: $LOGLEVEL"
        echo "📊 Environment Check:"
        echo "  - OPENAI_API_KEY length: ${#OPENAI_API_KEY}"
        echo "  - OPENAI_API_BASE: $OPENAI_API_BASE"
        echo "  - OPENAI_MODEL_NAME: $OPENAI_MODEL_NAME"
        echo "  - LOGLEVEL: $LOGLEVEL"

    - name: Debug Python Environment Variables  
      run: |
        python -c "
        import os
        print('🐍 Python Environment Variable Check:')
        api_key = os.environ.get('OPENAI_API_KEY', 'NOT_SET')
        if api_key != 'NOT_SET':
            print(f'  ✅ OPENAI_API_KEY: {api_key[:7]}... (length: {len(api_key)})')
        else:
            print('  ❌ OPENAI_API_KEY: NOT_SET')
        print(f'  🌐 OPENAI_API_BASE: {os.environ.get(\"OPENAI_API_BASE\", \"NOT_SET\")}')
        print(f'  🤖 OPENAI_MODEL_NAME: {os.environ.get(\"OPENAI_MODEL_NAME\", \"NOT_SET\")}')
        print(f'  📋 All OPENAI env vars:')
        for key, value in os.environ.items():
            if key.startswith('OPENAI'):
                print(f'    {key}: {value[:10] if len(value) > 10 else value}...')
        "

    - name: Validate API Key
      run: |
        echo "🔑 Testing API key validity with minimal OpenAI call..."
        python -c "
        import os
        try:
            from openai import OpenAI
            client = OpenAI(api_key=os.environ.get('OPENAI_API_KEY'))
            response = client.models.list()
            print('✅ API Key is VALID - OpenAI responded successfully')
            print(f'📊 Available models: {len(list(response.data))} models found')
        except Exception as e:
            print(f'❌ API Key is INVALID - Error: {e}')
            print('🔍 This explains why all API-dependent tests are failing')
            print('💡 The GitHub secret OPENAI_API_KEY needs to be updated with a valid key')
        "
      continue-on-error: true

    - name: Run Unit Tests
      run: |
        cd src/praisonai && python -m pytest tests/unit/ -v --tb=short --disable-warnings --cov=praisonai --cov-report=term-missing

    - name: Run Integration Tests  
      run: |
        cd src/praisonai && python -m pytest tests/integration/ -v --tb=short --disable-warnings

    - name: Debug Directory Structure
      run: |
        echo "🔍 Debugging directory structure for CrewAI tests..."
        cd src/praisonai
        echo "Current working directory: $(pwd)"
        echo "📁 Contents of current directory:"
        ls -la
        echo ""
        echo "📁 Contents of tests directory:"
        ls -la tests/ || echo "❌ tests/ directory not found"
        echo ""
        echo "📁 Contents of tests/integration:"
        ls -la tests/integration/ || echo "❌ tests/integration/ directory not found"
        echo ""
        echo "📁 Looking for crewai directory:"
        find . -name "crewai" -type d 2>/dev/null || echo "❌ No crewai directories found"
        echo ""
        echo "📁 Full directory tree of tests:"
        tree tests/ || find tests/ -type d 2>/dev/null || echo "❌ Cannot explore tests directory"

    - name: Test AutoGen Framework
      run: |
        echo "🤖 Testing AutoGen Framework Integration..."
        cd src/praisonai && python tests/test_runner.py --pattern autogen --verbose

    - name: Test CrewAI Framework
      run: |
        echo "⛵ Testing CrewAI Framework Integration..."
        cd src/praisonai
        echo "🔍 Trying test runner first..."
        python tests/test_runner.py --pattern crewai --verbose || {
          echo "❌ Test runner failed, trying direct pytest..."
          echo "📁 Current directory: $(pwd)"
          echo "📁 Looking for CrewAI tests..."
          find . -name "*crewai*" -type f 2>/dev/null
          echo "🧪 Trying direct pytest on integration/crewai..."
          python -m pytest tests/integration/crewai/ -v --tb=short --disable-warnings || {
            echo "❌ Direct path failed, trying relative path..."
            python -m pytest integration/crewai/ -v --tb=short --disable-warnings || {
              echo "❌ All CrewAI test attempts failed"
              exit 1
            }
          }
        }

    - name: Run Legacy Tests with API Key
      run: |
        echo "🧪 Running legacy tests with real API key..."
        cd src/praisonai && python -m pytest tests/test.py -v --tb=short --disable-warnings

    - name: Upload Coverage Reports
      if: matrix.python-version == '3.11'
      uses: actions/upload-artifact@v4
      with:
        name: coverage-reports
        path: |
          .coverage
          htmlcov/
        retention-days: 7